# Generated by Django 3.1.2 on 2021-08-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, verbose_name='Наименование')),
                ('description', models.CharField(max_length=30, verbose_name='Описание')),
                ('parameters', models.JSONField(null=True, verbose_name='Параметры')),
            ],
        ),
    ]
